BASE_URL = "https://www.tobeto.com"
LOGIN_URL = "https://tobeto.com/giris"
FIRST_LOGIN_BUTTON = ".border-light"
EMAIL_NAME = "email"
PASSWORD_NAME = "password"
LOGIN_BUTTON_XPATH = "//button[@class='btn btn-primary w-100 mt-6']"
LOGIN_MESSAGE_CSS = "div[class='toast-body']"
ERROR_MESSAGE_CSS = "div[class='toast-body']"
ERROR_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p"
FIRST_REGISTER_BUTTON = "//a[@href='/kayit-ol']"
NAME_NAME = "firstName"
SURNAME_NAME = "lastName"
ENTER_EMAIL = "email"
ENTER_PASSWORD = "password"
PASSWORD_AGAIN = "passwordAgain"
REGISTER_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
EXPLICIT_CONSENT_CHECKBOX = "contact"
MEMBERSHIP_CONTRAT_CHECKBOX = "membershipContrat"
EMAIL_CONFIRMATION_CHECKBOX = "emailConfirmation"
PHONE_CONFIRMATION_CHECKBOX = "phoneConfirmation"
ENTER_PHONE = "phoneNumber"
IFRAME_XPATH = "/html/body/div[4]/div/div/div/div/div/div[2]/div/div/div/iframe"
RECAPTCHA_CHECKBOX = "//div[@class='recaptcha-checkbox-border']"
CONTINUE_BUTTON_XPATH = "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
REGISTER_MESSAGE = "span[class='success-payment-text']"
INVALID_EMAIL_MESSAGE = "//p[.='Geçersiz e-posta adresi*']"
INVALID_PHONE_MESSAGE = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p"
INVALID_PHONE_MESSAGE2 = "//p[.='En fazla 10 karakter girebilirsiniz.']"
REGISTERED_EMAIL_MESSAGE = "toast-body"
PASSWORD_ERROR_MESSAGE = "toast-body"
NON_MATCHING_PASSWORDS = "toast-body"
TWO_ERRORS_MESSAGE = "toast-body"
SIGN_UP_MAIL_XPATH = "//*[@id='__next']/div/main/section/div/div/div/input"
SEND_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div/button"
SYSTEM_MESSAGE_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]"
PASSWORD_RESET_BUTTON = "//p[@class='text-decoration-none text-muted mt-5 d-block']"
ERROR_MESSAGE = "//*[@id='__next']/div/main/div[2]/div/div[2]"
IFRAME_ID = "exw-launcher-frame"
LAUNCHER_BUTTON = "launcher"
TOBETO_MESSAGE = "//section[@class='position-relative py-lg-20 bg-light-light py-sm-10']"
IFRAME_MESSAGE_BOX = "iframe[class='exw-conversation-container-frame']"
MINIMIZE_ICON = "svg[class='exw-minimize-button header-button']"
IFRAME_CSS = "iframe[class='exw-launcher-frame animated swing']"
CHATBOT_BUTTON = "button[id='launcher']"
IFRAME_END_CHAT = "exw-conversation-frame"
END_CHAT_BUTTON = "//*[name()='svg' and @class='exw-end-session-button header-button']"
END_CHAT_BOX = "h4[class='exw-title exw-with-avatar']"
MY_COURSES = "lessons-tab"
NOTIFICATION = "notification-tab"
SURVEY = "mySurvey-tab"
APPLY = "apply-tab"
COURSES_CONTROLLER = "//div[@id='all-lessons-tab-pane']/div[@class='row']/div[1]//a[.='Eğitime Git']"
NEWS_CONTROLLER = "//div[@id='notification-tab-pane']/div[@class='row']/div[1]//span[@class='type']"
SURVEY_CONTROLLER = "//p[.='Atanmış herhangi bir anketiniz bulunmamaktadır']"
HOME_PAGE_CONTROLLER = "h3"
HOME_PAGE = "//*[@id='__next']/div/nav/div[1]/ul/li[1]/a"
MY_PROFILE = "//*[@id='__next']/div/nav/div[1]/ul/li[2]/a"
MY_PROFILE_CONTROLLER = "//span[.='test automation']"
ASSESSMENTS_CONTROLLER = "//h3[contains(.,'Yetkinliklerini ücretsiz ölç, bilgilerini test et.')]"
ASSESSMENTS = "//*[@id='__next']/div/nav/div[1]/ul/li[3]/a"
CATALOG = "//*[@id='__next']/div/nav/div[1]/ul/li[4]/a"
CATALOG_CONTROLLER = "//span[.='Öğrenmeye başla !']"
CALENDAR = "//*[@id='__next']/div/nav/div[1]/ul/li[5]/a"
CALENDAR_CONTROLLER = ".fc-today-button"
ISTANBUL_CODING = "//*[@id='__next']/div/nav/div[1]/ul/li[6]/a"
ISTANBUL_CODING_CONTROLLER = ".header-text"
CLICK_MENU = ".name"
PROFILE_INFORMATION_BUTTON = "//*[@id='__next']/div/nav/div[1]/div/div/div[2]/ul/li[1]/a"
IDENTITY_NUMBER = "identifier"
COUNTRY_NAME = "country"
CITY = "city"
CITY_NAME = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[9]/select/option[8]"
DISTRICT = "district"
DISTRICT_NAME = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[10]/select/option[20]"
ADDRESS = "address"
ABOUT_ME = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[12]/textarea"
SAVE_BUTTON = ".btn-primary"
BIRTHDAY_INPUT = "birthday"
MESSAGE = "toast-body"
ERROR_MESSAGE_CONTROLLER = "toast-body"
NAME = "name"
SURNAME = "surname"
PHONE = "phoneNumber"
ERROR_MESSAGE_EMPTY_PROFILE = "span[class='text-danger']"
NAME_ERROR_MESSAGE_CONTROLLER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/span"
SURNAME_ERROR_MESSAGE_CONTROLLER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/span"
BIRTHDAY_ERROR_MESSAGE_CONTROLLER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/span"
IDENTITY_NUMBER_ERROR_MESSAGE_CONTROLLER = "i"
COUNTRY_ERROR_MESSAGE_CONTROLLER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[8]/span"
CITY_ERROR_MESSAGE_CONTROLLER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[9]/span"
DISTRICT_ERROR_MESSAGE_CONTROLLER = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[10]/span"
LOGOUT_BUTTON = "//ul[@class='profile dropdown-menu show']//a[contains(.,'Oturumu Kapat')]"
LOGOUT_CONTROLLER = "//button[@class='btn btn-primary w-100 mt-6']"
COURSE_CONTROLLER = "//div[@id='all-lessons-tab-pane']/div[@class='row']/div[1]//a[.='Eğitime Git']"
SEARCH_BUTTON = "search"
SHOW_MORE_BUTTON = "//*[@id='lessons-tab-pane']/div/div/div[2]"
COURSE_NOT_FOUND_CONTROLLER ="//*[@id='all-lessons-tab-pane']/div/p"
SELECT_INSTITUTION = '//*[@id="__next"]/div/main/div[2]/div[1]/div/div[2]/div/div[1]'
ISTANBUL_CODING_ID = "react-select-2-listbox"
FILTER_CONTROLLER = ".select__multi-value__label"
REMOVE_FILTERS = ".multi-btn"
REMOVE_FILTER_CONTROLLER = ".select__placeholder"
IN_PROGRESS = "//*[@id='myTab']/li[2]"
ALL_MY_COURSES = "//*[@id='myTab']/li[1]"
COMPLETED = "//*[@id='myTab']/li[3]"
GO_COURSE = "//div[@id='done-lessons-tab-pane']/div[@class='row']/div[1]//a[.='Eğitime Git']"
COURSE_CONTENT_CONTROLLER = "//span[.='İçerik']"
GO_ASENKRON_COURSE = "//div[@id='all-lessons-tab-pane']//div[14]//a[.='Eğitime Git']"
ASENKRON_COURSE_CONTROLLER = "[aria-selected='true'] .tabs-nav-title"
ICON_LIKE = "like-button"
ICON_DISLIKE = "//*[@id='main-content']"
VIEW_PERSON = "like-text"
LIKERS_CONTROLLER = ".ant-modal-title"
ABOUT_CONTENT_BUTTON = "//*[@id='rc-tabs-0-tab-about']/div/span"
ABOUT_CONTENT_CONTROLLER = "//strong[.='Başlangıç']"
GO_SENKRON_COURSE = "//div[@id='all-lessons-tab-pane']//div[15]//a[.='Eğitime Git']"
SENKRON_COURSE_CONTROLLER = "[aria-selected='true'] .tabs-nav-title"
VIEW_DETAIL_BUTTON = "//button[@class='ant-btn ant-btn-default ant-btn-lg ant-btn-block btn']/span[.='DETAY']"
DETAIL_CONTROLLER = "//span[.='SANAL SINIF']"
OPEN_RECORD_BUTTON = "//div[@id='activity-unit-detail']/div[@class='unit-detail-session-row LXP-Collapse']/div[2]//span[.='KAYDI AÇ']"
CALENDAR_CLASS = "calendar-btn"
CALENDAR_OUT = "/html/body/div[4]/div/div/div[1]/button"
EXPECTED_RESULT = "div[class='toast-body']"
DELETE_ICON = "div[class='lang-edit']:nth-child(1)>span[class='delete-lang']"
REGISTERED_LANGUAGES_1 = "div[class='tobeto-light-bg section-p my-langs'] div[class='lang-edit']:nth-child(1)"
NO_BUTTON = "div[class='alert-buttons'] button[class='btn btn-no my-3 ']"
YES_BUTTON = "div[class='alert-buttons'] button[class='btn btn-yes my-3']"
REQUIRED_FIELD_LANGUAGE = "div[class='row mb-2 mt-4']>div[class='col-md-6 col-12']:nth-child(1) p[style='text-align: start; color: red;']"
REQUIRED_FIELD_LEVEL = "div[class='row mb-2 mt-4']>div[class='col-md-6 col-12']:nth-child(2) p[style='text-align: start; color: red;']"
BEGIN_BUTTON = "div[class='details pack-bg-2']>button[class='btn btn-primary w-100 ']"
MY_EDUCATION_HISTORY= "div[class='p-2 py-4 mobile-sidebar']>a[class='btn mb-2 text-start w-100  sidebar-link ']:nth-child(3) span[class='sidebar-text']"
SELECT_EDUCATION_DROPDOWN = "select[name='EducationStatus']"
ENTER_UNIVERSITY = "input[name='University']"
DEPARTMENT_NAME = "input[name='Department']"
GRADUATION_YEAR = "input[class='form-control tobeto-input ']"
BEGIN_DATE = "div[class='react-datepicker__input-container ']>input[class='form-control tobeto-input']"
SELECT_DATE_CALENDAR = "div[class='react-datepicker__year-text react-datepicker__year-text--keyboard-selected react-datepicker__year-text--today']"
CONTINUE_CSS = "input[name='checkbox']"
SAVE_BUTTON_CSS = "button[class='btn btn-primary py-2 mb-3 d-inline-block mobil-btn']"
EXPECTED_RESULT_CSS = "div[class='toast-body']"
FOREIGN_LANGUAGE_LINK = "div[class='p-2 py-4 mobile-sidebar']>a[class='btn mb-2 text-start w-100  sidebar-link ']:nth-child(7) span[class='sidebar-text']"
SELECT_LANGUAGE_DROPDOWN ="select[name='languageName']"
SELECT_LEVEL_DROPDOWN = "select[name='proficiency']"
MY_EDUCATION_LINK = "div[class='p-2 py-4 mobile-sidebar']>a[class='btn mb-2 text-start w-100  sidebar-link ']:nth-child(3) span[class='sidebar-text']"
EXPECTED_RESULT_EMPTY = "span[class='text-danger']"






